DEFAULT_INPUT_FILE = 'Instance.xlsx'
DEFAULT_OUTPUT_FILE = 'Schedule.xlsx'
DEFAULT_MAXITERS = 10_000
DEFAULT_MINSCORE = 150000
SOLUTION_STREAMS_SHEET = 'streams'
SOLUTION_ABSTRACTS_SHEET = 'abstracts'
SOLUTION_STREAMS_VIOLATIONS_SHEET = 'streams_violations'
SOLUTION_ABSTRACTS_VIOLATIONS_SHEET = 'abstracts_violations'
